
// This file has been generated by the GUI designer. Do not modify.
namespace Empleado.cs
{
	public partial class GEmpresa
	{
		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox4;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.Alignment alignment8;

		private global::Gtk.Alignment alignment11;

		private global::Gtk.VBox vbox10;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label lblRUC;

		private global::Gtk.Entry entry1;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Label lblNombre;

		private global::Gtk.Entry entry3;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Label lblTelefono;

		private global::Gtk.Entry entry4;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label lblDireccion;

		private global::Gtk.Entry entry2;

		private global::Gtk.HBox hbox6;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Alignment alignment7;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.Alignment alignment10;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label lblSucursal;

		private global::Gtk.Entry entry5;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Label lblNombre1;

		private global::Gtk.Entry entry6;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Button btnSucursal;

		private global::Gtk.Button btnModificar;

		private global::Gtk.Button btnGuardar;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label21;

		private global::Gtk.HBox hbox19;

		private global::Gtk.VBox vbox12;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeview6;

		private global::Gtk.HBox hbox48;

		private global::Gtk.Alignment alignment32;

		private global::Gtk.Button btnVolver;

		private global::Gtk.Alignment alignment33;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Empleado.cs.GEmpresa
			this.Name = "Empleado.cs.GEmpresa";
			this.Title = global::Mono.Unix.Catalog.GetString("ADMINISTRACION");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Empleado.cs.GEmpresa.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("GESTION DE DATOS DE LA EMPRESA");
			this.vbox5.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			// Container child alignment5.Gtk.Container+ContainerChild
			this.alignment8 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			// Container child alignment8.Gtk.Container+ContainerChild
			this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.alignment8.Add(this.alignment11);
			this.alignment5.Add(this.alignment8);
			this.vbox7.Add(this.alignment5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.alignment5]));
			w4.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.lblRUC = new global::Gtk.Label();
			this.lblRUC.Name = "lblRUC";
			this.lblRUC.LabelProp = global::Mono.Unix.Catalog.GetString("Número RUC:");
			this.hbox10.Add(this.lblRUC);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.lblRUC]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.hbox10.Add(this.entry1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.entry1]));
			w6.Position = 1;
			this.vbox10.Add(this.hbox10);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox10]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.lblNombre = new global::Gtk.Label();
			this.lblNombre.Name = "lblNombre";
			this.lblNombre.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.hbox11.Add(this.lblNombre);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.lblNombre]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '•';
			this.hbox11.Add(this.entry3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.entry3]));
			w9.Position = 1;
			this.vbox10.Add(this.hbox11);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox11]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.lblTelefono = new global::Gtk.Label();
			this.lblTelefono.Name = "lblTelefono";
			this.lblTelefono.LabelProp = global::Mono.Unix.Catalog.GetString("Telefono:");
			this.hbox12.Add(this.lblTelefono);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.lblTelefono]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.hbox12.Add(this.entry4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.entry4]));
			w12.Position = 1;
			this.vbox10.Add(this.hbox12);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox12]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox7.Add(this.vbox10);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox10]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox4.Add(this.vbox7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox7]));
			w15.Position = 0;
			this.vbox6.Add(this.hbox4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox4]));
			w16.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblDireccion = new global::Gtk.Label();
			this.lblDireccion.Name = "lblDireccion";
			this.lblDireccion.LabelProp = global::Mono.Unix.Catalog.GetString("Dirección:");
			this.hbox5.Add(this.lblDireccion);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.lblDireccion]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.hbox5.Add(this.entry2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry2]));
			w18.Position = 1;
			this.vbox6.Add(this.hbox5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			// Container child alignment7.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			// Container child alignment9.Gtk.Container+ContainerChild
			this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			this.alignment9.Add(this.alignment10);
			this.vbox11.Add(this.alignment9);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.alignment9]));
			w21.Position = 0;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.lblSucursal = new global::Gtk.Label();
			this.lblSucursal.Name = "lblSucursal";
			this.lblSucursal.LabelProp = global::Mono.Unix.Catalog.GetString("ID Sucursal:");
			this.hbox13.Add(this.lblSucursal);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.lblSucursal]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.entry5 = new global::Gtk.Entry();
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.IsEditable = true;
			this.entry5.InvisibleChar = '•';
			this.hbox13.Add(this.entry5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.entry5]));
			w23.Position = 1;
			this.vbox11.Add(this.hbox13);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox13]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.lblNombre1 = new global::Gtk.Label();
			this.lblNombre1.Name = "lblNombre1";
			this.lblNombre1.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.hbox15.Add(this.lblNombre1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.lblNombre1]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.entry6 = new global::Gtk.Entry();
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.InvisibleChar = '•';
			this.hbox15.Add(this.entry6);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.entry6]));
			w26.Position = 1;
			this.vbox11.Add(this.hbox15);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox15]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.alignment7.Add(this.vbox11);
			this.vbox8.Add(this.alignment7);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.alignment7]));
			w29.Position = 0;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.btnSucursal = new global::Gtk.Button();
			this.btnSucursal.CanFocus = true;
			this.btnSucursal.Name = "btnSucursal";
			this.btnSucursal.UseUnderline = true;
			this.btnSucursal.BorderWidth = ((uint)(6));
			this.btnSucursal.Label = global::Mono.Unix.Catalog.GetString("Nueva Sucursal");
			this.hbox16.Add(this.btnSucursal);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.btnSucursal]));
			w30.Position = 0;
			// Container child hbox16.Gtk.Box+BoxChild
			this.btnModificar = new global::Gtk.Button();
			this.btnModificar.CanFocus = true;
			this.btnModificar.Name = "btnModificar";
			this.btnModificar.UseUnderline = true;
			this.btnModificar.BorderWidth = ((uint)(6));
			this.btnModificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.hbox16.Add(this.btnModificar);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.btnModificar]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.BorderWidth = ((uint)(6));
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.hbox16.Add(this.btnGuardar);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.btnGuardar]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox8.Add(this.hbox16);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox16]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox6.Add(this.vbox8);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox8]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox6.Add(this.hbox6);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
			w35.Position = 2;
			this.vbox5.Add(this.vbox6);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox6]));
			w36.Position = 1;
			this.vbox2.Add(this.vbox5);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox5]));
			w37.Position = 0;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.hbox2.Add(this.label21);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label21]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview5 = new global::Gtk.TreeView();
			this.treeview5.CanFocus = true;
			this.treeview5.Name = "treeview5";
			this.GtkScrolledWindow.Add(this.treeview5);
			this.vbox12.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.GtkScrolledWindow]));
			w43.Position = 0;
			// Container child vbox12.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview6 = new global::Gtk.TreeView();
			this.treeview6.CanFocus = true;
			this.treeview6.Name = "treeview6";
			this.GtkScrolledWindow1.Add(this.treeview6);
			this.vbox12.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.GtkScrolledWindow1]));
			w45.Position = 1;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox48 = new global::Gtk.HBox();
			this.hbox48.Name = "hbox48";
			this.hbox48.Spacing = 6;
			// Container child hbox48.Gtk.Box+BoxChild
			this.alignment32 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment32.Name = "alignment32";
			this.hbox48.Add(this.alignment32);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox48[this.alignment32]));
			w46.Position = 0;
			// Container child hbox48.Gtk.Box+BoxChild
			this.btnVolver = new global::Gtk.Button();
			this.btnVolver.CanFocus = true;
			this.btnVolver.Name = "btnVolver";
			this.btnVolver.UseUnderline = true;
			this.btnVolver.Label = global::Mono.Unix.Catalog.GetString("Volver al menú principal");
			this.hbox48.Add(this.btnVolver);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox48[this.btnVolver]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox48.Gtk.Box+BoxChild
			this.alignment33 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment33.Name = "alignment33";
			this.hbox48.Add(this.alignment33);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox48[this.alignment33]));
			w48.Position = 2;
			this.vbox12.Add(this.hbox48);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox48]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			this.hbox19.Add(this.vbox12);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.vbox12]));
			w50.Position = 0;
			this.hbox1.Add(this.hbox19);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox19]));
			w51.Position = 2;
			this.GtkAlignment2.Add(this.hbox1);
			this.GtkAlignment1.Add(this.GtkAlignment2);
			this.Add(this.GtkAlignment1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 840;
			this.DefaultHeight = 330;
			this.Show();
		}
	}
}
