
// This file has been generated by the GUI designer. Do not modify.
namespace Empleado.cs
{
	public partial class GDepartamentosandPlazas
	{
		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox4;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.Alignment alignment8;

		private global::Gtk.Alignment alignment11;

		private global::Gtk.VBox vbox10;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label2;

		private global::Gtk.Entry entry1;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Label label22;

		private global::Gtk.Label label4;

		private global::Gtk.Entry entry3;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Label label5;

		private global::Gtk.Entry entry4;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.Entry entry2;

		private global::Gtk.HBox hbox6;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Alignment alignment7;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.Alignment alignment10;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Button button10;

		private global::Gtk.Button button9;

		private global::Gtk.Button button8;

		private global::Gtk.Button button7;

		private global::Gtk.Alignment alignment12;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label21;

		private global::Gtk.Entry entry13;

		private global::Gtk.Button btnBuscar;

		private global::Gtk.VBox vbox9;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeview3;

		private global::Gtk.HBox hbox45;

		private global::Gtk.Alignment alignment26;

		private global::Gtk.Button btnVolver;

		private global::Gtk.Alignment alignment27;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Empleado.cs.GDepartamentosandPlazas
			this.Name = "Empleado.cs.GDepartamentosandPlazas";
			this.Title = global::Mono.Unix.Catalog.GetString("ADMINISTRACION");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Empleado.cs.GDepartamentosandPlazas.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("GESTION DE DEPARTAMENTOS Y AREAS");
			this.vbox5.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			// Container child alignment5.Gtk.Container+ContainerChild
			this.alignment8 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			// Container child alignment8.Gtk.Container+ContainerChild
			this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.alignment8.Add(this.alignment11);
			this.alignment5.Add(this.alignment8);
			this.vbox7.Add(this.alignment5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.alignment5]));
			w4.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("ID Departamento:");
			this.hbox10.Add(this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.hbox10.Add(this.entry1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.entry1]));
			w6.Position = 1;
			this.vbox10.Add(this.hbox10);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox10]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("              Nombre:    ");
			this.hbox11.Add(this.label22);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label22]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.hbox11.Add(this.label4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label4]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '•';
			this.hbox11.Add(this.entry3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.entry3]));
			w10.Position = 2;
			this.vbox10.Add(this.hbox11);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox11]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("                 ID Area:     ");
			this.hbox12.Add(this.label5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label5]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.hbox12.Add(this.entry4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.entry4]));
			w13.Position = 1;
			this.vbox10.Add(this.hbox12);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox12]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox7.Add(this.vbox10);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox10]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox4.Add(this.vbox7);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox7]));
			w16.Position = 0;
			this.vbox6.Add(this.hbox4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox4]));
			w17.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("              Nombre:      ");
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.hbox5.Add(this.entry2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry2]));
			w19.Position = 1;
			this.vbox6.Add(this.hbox5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			// Container child alignment7.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			// Container child alignment9.Gtk.Container+ContainerChild
			this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			this.alignment9.Add(this.alignment10);
			this.vbox11.Add(this.alignment9);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.alignment9]));
			w22.Position = 0;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString("Nuevo Departamento");
			this.hbox13.Add(this.button10);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button10]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString("Nueva Area");
			this.hbox13.Add(this.button9);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button9]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.hbox13.Add(this.button8);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button8]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox11.Add(this.hbox13);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox13]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.vbox11.Add(this.button7);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.button7]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.alignment7.Add(this.vbox11);
			this.vbox8.Add(this.alignment7);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.alignment7]));
			w29.Position = 0;
			// Container child vbox8.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.vbox8.Add(this.alignment12);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.alignment12]));
			w30.Position = 1;
			this.hbox6.Add(this.vbox8);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox8]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox6.Add(this.hbox6);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
			w32.Position = 2;
			this.vbox5.Add(this.vbox6);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox6]));
			w33.Position = 1;
			this.vbox2.Add(this.vbox5);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox5]));
			w34.Position = 0;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar ID departamento:");
			this.hbox2.Add(this.label21);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label21]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entry13 = new global::Gtk.Entry();
			this.entry13.CanFocus = true;
			this.entry13.Name = "entry13";
			this.entry13.IsEditable = true;
			this.entry13.InvisibleChar = '•';
			this.hbox2.Add(this.entry13);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entry13]));
			w37.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox2.Add(this.btnBuscar);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnBuscar]));
			w38.Position = 2;
			w38.Expand = false;
			w38.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.GtkScrolledWindow.Add(this.treeview2);
			this.vbox9.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.GtkScrolledWindow]));
			w41.Position = 0;
			// Container child vbox9.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview3 = new global::Gtk.TreeView();
			this.treeview3.CanFocus = true;
			this.treeview3.Name = "treeview3";
			this.GtkScrolledWindow1.Add(this.treeview3);
			this.vbox9.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.GtkScrolledWindow1]));
			w43.Position = 1;
			this.vbox1.Add(this.vbox9);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox9]));
			w44.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox45 = new global::Gtk.HBox();
			this.hbox45.Name = "hbox45";
			this.hbox45.Spacing = 6;
			// Container child hbox45.Gtk.Box+BoxChild
			this.alignment26 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment26.Name = "alignment26";
			this.hbox45.Add(this.alignment26);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.alignment26]));
			w45.Position = 0;
			// Container child hbox45.Gtk.Box+BoxChild
			this.btnVolver = new global::Gtk.Button();
			this.btnVolver.CanFocus = true;
			this.btnVolver.Name = "btnVolver";
			this.btnVolver.UseUnderline = true;
			this.btnVolver.Label = global::Mono.Unix.Catalog.GetString("Volver al menú principal");
			this.hbox45.Add(this.btnVolver);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.btnVolver]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox45.Gtk.Box+BoxChild
			this.alignment27 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment27.Name = "alignment27";
			this.hbox45.Add(this.alignment27);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.alignment27]));
			w47.Position = 2;
			this.vbox1.Add(this.hbox45);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox45]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w49.Position = 1;
			this.GtkAlignment2.Add(this.hbox1);
			this.GtkAlignment1.Add(this.GtkAlignment2);
			this.GtkAlignment.Add(this.GtkAlignment1);
			this.Add(this.GtkAlignment);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 773;
			this.DefaultHeight = 440;
			this.Show();
		}
	}
}
