
// This file has been generated by the GUI designer. Do not modify.
namespace Empleado.cs
{
	public partial class Menu
	{
		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.HBox hbox4;

		private global::Gtk.VBox vbox12;

		private global::Gtk.VBox vbox13;

		private global::Gtk.Label label5;

		private global::Gtk.Button btnGEmpleados;

		private global::Gtk.Button btnBajaEmpleado;

		private global::Gtk.VBox vbox14;

		private global::Gtk.Button btnCEMpleado;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.Label label6;

		private global::Gtk.VBox vbox15;

		private global::Gtk.Button btnPNomina;

		private global::Gtk.Button btnGVacaciones;

		private global::Gtk.VBox vbox16;

		private global::Gtk.Button btnGBono;

		private global::Gtk.Button btnGDeducciones;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.Alignment alignment11;

		private global::Gtk.VBox vbox17;

		private global::Gtk.VBox vbox18;

		private global::Gtk.Label label7;

		private global::Gtk.Button btnGEmpresa;

		private global::Gtk.Button btnGDepartamento;

		private global::Gtk.VBox vbox19;

		private global::Gtk.Alignment alignment6;

		private global::Gtk.VBox vbox21;

		private global::Gtk.Button btnGContrato;

		private global::Gtk.VBox vbox24;

		private global::Gtk.Button btnGPlaza;

		private global::Gtk.Alignment alignment12;

		private global::Gtk.Label label8;

		private global::Gtk.Button btnGUsuarios;

		private global::Gtk.VBox vbox20;

		private global::Gtk.Alignment alignment13;

		private global::Gtk.Alignment alignment15;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.Label label10;

		private global::Gtk.VBox vbox22;

		private global::Gtk.Button btnCHorarios;

		private global::Gtk.Button btnGMonedas;

		private global::Gtk.VBox vbox23;

		private global::Gtk.Alignment alignment10;

		private global::Gtk.Alignment alignment14;

		private global::Gtk.Button btnGEmpleado;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Empleado.cs.Menu
			this.Name = "Empleado.cs.Menu";
			this.Title = global::Mono.Unix.Catalog.GetString("Menu");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Empleado.cs.Menu.Gtk.Container+ContainerChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Empleados");
			this.vbox13.Add(this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.label5]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(10));
			// Container child vbox13.Gtk.Box+BoxChild
			this.btnGEmpleados = new global::Gtk.Button();
			this.btnGEmpleados.CanFocus = true;
			this.btnGEmpleados.Name = "btnGEmpleados";
			this.btnGEmpleados.UseUnderline = true;
			this.btnGEmpleados.Label = global::Mono.Unix.Catalog.GetString("Gestion de Empleados");
			this.vbox13.Add(this.btnGEmpleados);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.btnGEmpleados]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.btnBajaEmpleado = new global::Gtk.Button();
			this.btnBajaEmpleado.CanFocus = true;
			this.btnBajaEmpleado.Name = "btnBajaEmpleado";
			this.btnBajaEmpleado.UseUnderline = true;
			this.btnBajaEmpleado.Label = global::Mono.Unix.Catalog.GetString("Baja de Empleado");
			this.vbox13.Add(this.btnBajaEmpleado);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.btnBajaEmpleado]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox12.Add(this.vbox13);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.vbox13]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.btnCEMpleado = new global::Gtk.Button();
			this.btnCEMpleado.CanFocus = true;
			this.btnCEMpleado.Name = "btnCEMpleado";
			this.btnCEMpleado.UseUnderline = true;
			this.btnCEMpleado.Label = global::Mono.Unix.Catalog.GetString("Contratación de Empleado");
			this.vbox14.Add(this.btnCEMpleado);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.btnCEMpleado]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.vbox14.Add(this.alignment4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.alignment4]));
			w6.Position = 1;
			// Container child vbox14.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Nómina");
			this.vbox14.Add(this.label6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.label6]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox12.Add(this.vbox14);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.vbox14]));
			w8.Position = 1;
			w8.Padding = ((uint)(4));
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.btnPNomina = new global::Gtk.Button();
			this.btnPNomina.CanFocus = true;
			this.btnPNomina.Name = "btnPNomina";
			this.btnPNomina.UseUnderline = true;
			this.btnPNomina.Label = global::Mono.Unix.Catalog.GetString("Pago de Nómina");
			this.vbox15.Add(this.btnPNomina);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.btnPNomina]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.btnGVacaciones = new global::Gtk.Button();
			this.btnGVacaciones.CanFocus = true;
			this.btnGVacaciones.Name = "btnGVacaciones";
			this.btnGVacaciones.UseUnderline = true;
			this.btnGVacaciones.Label = global::Mono.Unix.Catalog.GetString("Gestión de Vacaciones");
			this.vbox15.Add(this.btnGVacaciones);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.btnGVacaciones]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.btnGBono = new global::Gtk.Button();
			this.btnGBono.CanFocus = true;
			this.btnGBono.Name = "btnGBono";
			this.btnGBono.UseUnderline = true;
			this.btnGBono.Label = global::Mono.Unix.Catalog.GetString("Gestión de Bonos");
			this.vbox16.Add(this.btnGBono);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.btnGBono]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.btnGDeducciones = new global::Gtk.Button();
			this.btnGDeducciones.CanFocus = true;
			this.btnGDeducciones.Name = "btnGDeducciones";
			this.btnGDeducciones.UseUnderline = true;
			this.btnGDeducciones.Label = global::Mono.Unix.Catalog.GetString("Gestión de Deducciones");
			this.vbox16.Add(this.btnGDeducciones);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.btnGDeducciones]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.vbox16.Add(this.alignment5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.alignment5]));
			w13.Position = 2;
			this.vbox15.Add(this.vbox16);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.vbox16]));
			w14.Position = 2;
			this.vbox12.Add(this.vbox15);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.vbox15]));
			w15.Position = 2;
			this.hbox4.Add(this.vbox12);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox12]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.hbox4.Add(this.alignment11);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.alignment11]));
			w17.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.vbox18 = new global::Gtk.VBox();
			this.vbox18.Name = "vbox18";
			this.vbox18.Spacing = 6;
			// Container child vbox18.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Administración");
			this.vbox18.Add(this.label7);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.label7]));
			w18.Position = 0;
			w18.Padding = ((uint)(10));
			// Container child vbox18.Gtk.Box+BoxChild
			this.btnGEmpresa = new global::Gtk.Button();
			this.btnGEmpresa.CanFocus = true;
			this.btnGEmpresa.Name = "btnGEmpresa";
			this.btnGEmpresa.UseUnderline = true;
			this.btnGEmpresa.Label = global::Mono.Unix.Catalog.GetString("Gestión de Datos de la Empresa");
			this.vbox18.Add(this.btnGEmpresa);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.btnGEmpresa]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox18.Gtk.Box+BoxChild
			this.btnGDepartamento = new global::Gtk.Button();
			this.btnGDepartamento.CanFocus = true;
			this.btnGDepartamento.Name = "btnGDepartamento";
			this.btnGDepartamento.UseUnderline = true;
			this.btnGDepartamento.Label = global::Mono.Unix.Catalog.GetString("Gestón de Departamentos y Areas");
			this.vbox18.Add(this.btnGDepartamento);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.btnGDepartamento]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox17.Add(this.vbox18);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.vbox18]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.vbox19 = new global::Gtk.VBox();
			this.vbox19.Name = "vbox19";
			this.vbox19.Spacing = 6;
			// Container child vbox19.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			// Container child alignment6.Gtk.Container+ContainerChild
			this.vbox21 = new global::Gtk.VBox();
			this.vbox21.Name = "vbox21";
			this.vbox21.Spacing = 6;
			// Container child vbox21.Gtk.Box+BoxChild
			this.btnGContrato = new global::Gtk.Button();
			this.btnGContrato.CanFocus = true;
			this.btnGContrato.Name = "btnGContrato";
			this.btnGContrato.UseUnderline = true;
			this.btnGContrato.Label = global::Mono.Unix.Catalog.GetString("Gestión de Contratos");
			this.vbox21.Add(this.btnGContrato);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.btnGContrato]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox21.Gtk.Box+BoxChild
			this.vbox24 = new global::Gtk.VBox();
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			// Container child vbox24.Gtk.Box+BoxChild
			this.btnGPlaza = new global::Gtk.Button();
			this.btnGPlaza.CanFocus = true;
			this.btnGPlaza.Name = "btnGPlaza";
			this.btnGPlaza.UseUnderline = true;
			this.btnGPlaza.Label = global::Mono.Unix.Catalog.GetString("Gestión de Plazas");
			this.vbox24.Add(this.btnGPlaza);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.btnGPlaza]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.vbox24.Add(this.alignment12);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.alignment12]));
			w24.Position = 1;
			this.vbox21.Add(this.vbox24);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.vbox24]));
			w25.Position = 1;
			this.alignment6.Add(this.vbox21);
			this.vbox19.Add(this.alignment6);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.alignment6]));
			w27.Position = 0;
			// Container child vbox19.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Seguridad");
			this.label8.UseUnderline = true;
			this.label8.Justify = ((global::Gtk.Justification)(3));
			this.vbox19.Add(this.label8);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.label8]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox19.Gtk.Box+BoxChild
			this.btnGUsuarios = new global::Gtk.Button();
			this.btnGUsuarios.CanFocus = true;
			this.btnGUsuarios.Name = "btnGUsuarios";
			this.btnGUsuarios.UseUnderline = true;
			this.btnGUsuarios.Label = global::Mono.Unix.Catalog.GetString("Gestión de Usuarios");
			this.vbox19.Add(this.btnGUsuarios);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.btnGUsuarios]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox17.Add(this.vbox19);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.vbox19]));
			w30.Position = 1;
			// Container child vbox17.Gtk.Box+BoxChild
			this.vbox20 = new global::Gtk.VBox();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			// Container child alignment13.Gtk.Container+ContainerChild
			this.alignment15 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment15.Name = "alignment15";
			this.alignment13.Add(this.alignment15);
			this.vbox20.Add(this.alignment13);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.alignment13]));
			w32.Position = 0;
			// Container child vbox20.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			// Container child alignment9.Gtk.Container+ContainerChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Configuración");
			this.alignment9.Add(this.label10);
			this.vbox20.Add(this.alignment9);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.alignment9]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.vbox22 = new global::Gtk.VBox();
			this.vbox22.Name = "vbox22";
			this.vbox22.Spacing = 6;
			// Container child vbox22.Gtk.Box+BoxChild
			this.btnCHorarios = new global::Gtk.Button();
			this.btnCHorarios.CanFocus = true;
			this.btnCHorarios.Name = "btnCHorarios";
			this.btnCHorarios.UseUnderline = true;
			this.btnCHorarios.Label = global::Mono.Unix.Catalog.GetString("Control de Horario");
			this.vbox22.Add(this.btnCHorarios);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.btnCHorarios]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox22.Gtk.Box+BoxChild
			this.btnGMonedas = new global::Gtk.Button();
			this.btnGMonedas.CanFocus = true;
			this.btnGMonedas.Name = "btnGMonedas";
			this.btnGMonedas.UseUnderline = true;
			this.btnGMonedas.Label = global::Mono.Unix.Catalog.GetString("Gestión de Moneda");
			this.vbox22.Add(this.btnGMonedas);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.btnGMonedas]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox22.Gtk.Box+BoxChild
			this.vbox23 = new global::Gtk.VBox();
			this.vbox23.Name = "vbox23";
			this.vbox23.Spacing = 6;
			// Container child vbox23.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			// Container child alignment10.Gtk.Container+ContainerChild
			this.alignment14 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment14.Name = "alignment14";
			// Container child alignment14.Gtk.Container+ContainerChild
			this.btnGEmpleado = new global::Gtk.Button();
			this.btnGEmpleado.CanFocus = true;
			this.btnGEmpleado.Name = "btnGEmpleado";
			this.btnGEmpleado.UseUnderline = true;
			this.btnGEmpleado.Label = global::Mono.Unix.Catalog.GetString("Pruebita");
			this.alignment14.Add(this.btnGEmpleado);
			this.alignment10.Add(this.alignment14);
			this.vbox23.Add(this.alignment10);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.alignment10]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox22.Add(this.vbox23);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.vbox23]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox20.Add(this.vbox22);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.vbox22]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			this.vbox17.Add(this.vbox20);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.vbox20]));
			w42.Position = 2;
			this.hbox4.Add(this.vbox17);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox17]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			this.GtkAlignment.Add(this.hbox4);
			this.frame2.Add(this.GtkAlignment);
			this.Add(this.frame2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 580;
			this.DefaultHeight = 461;
			this.Show();
			this.btnGEmpleados.Clicked += new global::System.EventHandler(this.OnBtnGEmpleadosClicked);
			this.btnBajaEmpleado.Clicked += new global::System.EventHandler(this.OnBtnBajaEmpleadoClicked);
			this.btnCEMpleado.Clicked += new global::System.EventHandler(this.OnBtnCEMpleadoClicked);
			this.btnPNomina.Clicked += new global::System.EventHandler(this.OnBtnPNominaClicked);
			this.btnGVacaciones.Clicked += new global::System.EventHandler(this.OnBtnGVacacionesClicked);
			this.btnGBono.Clicked += new global::System.EventHandler(this.OnBtnGBonoClicked);
			this.btnGDeducciones.Clicked += new global::System.EventHandler(this.OnBtnGDeduccionesClicked);
			this.btnGEmpresa.Clicked += new global::System.EventHandler(this.OnBtnGEmpresaClicked);
			this.btnGDepartamento.Clicked += new global::System.EventHandler(this.OnBtnGDepartamentoClicked);
			this.btnGContrato.Clicked += new global::System.EventHandler(this.OnBtnGContratoClicked);
			this.btnGPlaza.Clicked += new global::System.EventHandler(this.OnBtnGPlazaClicked);
			this.btnGUsuarios.Clicked += new global::System.EventHandler(this.OnBtnGUsuariosClicked);
			this.btnCHorarios.Clicked += new global::System.EventHandler(this.OnBtnCHorariosClicked);
			this.btnGMonedas.Clicked += new global::System.EventHandler(this.OnBtnGMonedasClicked);
			this.btnGEmpleado.Clicked += new global::System.EventHandler(this.OnBtnGEmpleadoClicked);
		}
	}
}
